### ISSUE TITLE
[error] "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions....

### ISSUE THREAD

**Issue by myyrakle** [aws-samples/aws-cdk-amplify-with-waf#8]
Due to the deprecation of the Lambda version that was previously created internally, the project cannot be used as is.

To use it, you need to upgrade the aws-cdk version. I confirmed it works.
![image](https://github.com/aws-samples/aws-cdk-amplify-with-waf/assets/16988115/155b7090-a8a2-4c7e-bba6-f5029ee945d1)

**Comment by YutaOkoshi** [comment]
https://github.com/aws-samples/aws-cdk-amplify-with-waf/pull/10
At least I got it working with this PR change.
